#!/bin/bash

xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/brightness-exponential -s true --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/blank-on-ac -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/blank-on-battery -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/brightness-on-battery -s 9 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/brightness-switch -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/brightness-switch-restore-on-exit -s 0 --create 
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-enabled -s true --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-ac-off -s  0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-ac-sleep -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-battery-off -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/dpms-on-battery-sleep -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/inactivity-sleep-mode-on-battery -s 1 --create 
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-ac -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lid-action-on-battery -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/lock-screen-suspend-hibernate -s true --create 
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/logind-handle-lid-switch -s false --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/power-button-action -s 3 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/show-panel-label -s 0 --create
xfconf-query -c xfce4-power-manager -p /xfce4-power-manager/show-tray-icon -s false --create
